services:
  mongodb:
    image: mongo:4.4
    container_name: mongodb
    ports:
      - "27017:27017"  
    volumes:
      - mongodb-data:/data/db  
      - ./init.js:/docker-entrypoint-initdb.d/init.js:ro
    environment:
      - MONGO_INITDB_DATABASE=e22102349

  manager-api:
    image: managers-api  
    container_name: manager-api
    ports:
      - "8082:8080"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/e22102349
    depends_on:
      - mongodb  

volumes:
  mongodb-data:
