version: '3.7'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"  
    volumes:
      - mongodb-data:/data/db  

  manager-api:
    image: managers-api  
    container_name: manager-api
    ports:
      - "8080:8080"  
    environment:
      - MONGO_URI=mongodb://mongodb:27017  
    depends_on:
      - mongodb  

volumes:
  mongodb-data: 